/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Business.Fachada;
import Business.LeilaoException;
import Business.Validadores.ValidadorBem;
import Business.Validadores.ValidadorLeilao;
import Data.DAOException;
import Domain.Bem;
import Domain.Categoria;
import Domain.FormaLance;
import Domain.Natureza;
import Domain.Usuario;
import java.math.BigDecimal;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Eduardo
 */
public class DlgLeilao extends javax.swing.JDialog {
    private final Fachada fachada;
    private List<Bem> listaBens;
    private DefaultListModel modelBem = new DefaultListModel();
    /**
     * Creates new form DlgLeilao
     * @param parent
     * @param modal
     * @param fachada
     */
     public DlgLeilao(java.awt.Frame parent, boolean modal, Fachada fachada) {
        super(parent, modal);
        this.fachada = fachada;
        initComponents();
        this.setLocationRelativeTo(null);
        populaCampos();
        listaBens = new ArrayList<Bem>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JTextField();
        cmbForma = new javax.swing.JComboBox();
        txtDataFim = new javax.swing.JTextField();
        txtValorLote = new javax.swing.JTextField();
        cmbNatureza = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDescricaoBreve = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        btnAddBem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBens = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricaoCompleta = new javax.swing.JTextArea();
        btnSalvarLeilao = new javax.swing.JButton();
        btnCancelaLeilao = new javax.swing.JButton();
        cmbUsuario = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        txtHoraFim = new javax.swing.JTextField();

        jLabel10.setText("Descrição Completa:");

        setResizable(false);

        jLabel1.setText("Cadastrar Leilao");

        jLabel2.setText("DataInicio:");

        jLabel4.setText("Data Fim:");

        jLabel5.setText("Hora Fim:");

        jLabel6.setText("Natureza:");

        jLabel7.setText("Forma:");

        jLabel8.setText("Valor Lote:");

        jLabel3.setText("Adicionar Bens");

        jLabel9.setText("Descrição breve:");

        jLabel11.setText("Categoria:");

        jLabel12.setText("Descrição Completa:");

        btnAddBem.setText("Adicionar Bem");
        btnAddBem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBemActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstBens);

        jLabel13.setText("Bens Adicionados:");

        txtDescricaoCompleta.setColumns(20);
        txtDescricaoCompleta.setRows(5);
        jScrollPane2.setViewportView(txtDescricaoCompleta);

        btnSalvarLeilao.setText("Salvar");
        btnSalvarLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLeilaoActionPerformed(evt);
            }
        });

        btnCancelaLeilao.setText("Cancelar");
        btnCancelaLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaLeilaoActionPerformed(evt);
            }
        });

        cmbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioActionPerformed(evt);
            }
        });

        jLabel14.setText("Usuário:");

        jLabel15.setText("Hora Inicio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(359, 359, 359)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddBem)
                                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoBreve, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarLeilao)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelaLeilao)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(cmbNatureza, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2))
                                        .addComponent(cmbForma, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValorLote)
                            .addComponent(cmbUsuario, 0, 108, Short.MAX_VALUE)
                            .addComponent(txtHoraFim)
                            .addComponent(txtHoraInicio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel1)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtValorLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cmbNatureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtDescricaoBreve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddBem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelaLeilao)
                        .addComponent(btnSalvarLeilao)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populaCampos(){
        try{
            for (Usuario usu : fachada.buscarTodosUsuarios())
                cmbUsuario.addItem(usu);
            for (Categoria cat : fachada.buscarTodaCategorias())
                cmbCategoria.addItem(cat);
            cmbNatureza.addItem(Natureza.OFERTA);
            cmbNatureza.addItem(Natureza.DEMANDA);
            cmbForma.addItem(FormaLance.ABERTO);
            cmbForma.addItem(FormaLance.FECHADO);
            
            lstBens.setModel(modelBem);
        }catch(DAOException e) {
            
        }
        
    }
    
    private void btnSalvarLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLeilaoActionPerformed
        Calendar dataInicio = Calendar.getInstance();
        Calendar dataFim = Calendar.getInstance();
        
        String[] dtIniStr = txtDataInicio.getText().split("/");
        String[] dtFimStr = txtDataFim.getText().split("/");
        
        String[] hrIniStr = txtHoraInicio.getText().split(":");
        String[] hrFimStr = txtHoraFim.getText().split(":");

        if (!ValidadorLeilao.getInstance().validaDatas(dtIniStr, dtFimStr)) {
            JOptionPane.showMessageDialog(null, "Data(s) incorreta(s)(dd/mm/yyyy).");
        } else if (!ValidadorLeilao.getInstance().validaHoras(hrIniStr, hrFimStr)) {
            JOptionPane.showMessageDialog(null, "Hora(s) incorreta(s)(hh:mm).");
        } else if(!ValidadorLeilao.getInstance().validaValorLote(txtValorLote.getText())) {
            JOptionPane.showMessageDialog(null, "Valor lote incorreto.");
        } else {
            try {
                dataFim.set(Integer.valueOf(dtFimStr[2]), Integer.valueOf(dtFimStr[1]), Integer.valueOf(dtFimStr[0]));
                dataInicio.set(Integer.valueOf(dtIniStr[2]), Integer.valueOf(dtIniStr[1]), Integer.valueOf(dtIniStr[0]));
                Time horaInicio = new Time(Integer.valueOf(hrIniStr[0]), Integer.valueOf(hrIniStr[1]), 0);
                Time horaFim = new Time(Integer.valueOf(hrFimStr[0]), Integer.valueOf(hrFimStr[1]), 0);
                
                fachada.novoLeilao(
                        dataInicio.getTime(), 
                        horaInicio, 
                        dataFim.getTime(), 
                        horaFim, 
                        (Natureza) cmbNatureza.getSelectedItem(),
                        (FormaLance) cmbForma.getSelectedItem(), 
                        new BigDecimal(txtValorLote.getText()), 
                        (Usuario) cmbUsuario.getSelectedItem(),
                        listaBens);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Criado com sucesso.");
            } catch (LeilaoException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSalvarLeilaoActionPerformed

    private void btnCancelaLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaLeilaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaLeilaoActionPerformed

    private void btnAddBemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBemActionPerformed

        if(!ValidadorBem.getInstance().validaDescBreve(txtDescricaoBreve.getText()))
            JOptionPane.showMessageDialog(null, "Descrição breve obrigatória(5 <= descrição breve <= 50).");
        else if(!ValidadorBem.getInstance().validaDescCompleta(txtDescricaoCompleta.getText()))
            JOptionPane.showMessageDialog(null, "Descrição completa obrigatória(5 <= descrição completa <= 255).");
        else {
            Bem bem = new Bem(0,txtDescricaoBreve.getText(), txtDescricaoCompleta.getText(),(Categoria) cmbCategoria.getSelectedItem(),0);
            listaBens.add(bem);
            modelBem.add(0, bem);
            txtDescricaoBreve.setText("");
            txtDescricaoCompleta.setText("");
        }
    }//GEN-LAST:event_btnAddBemActionPerformed

    private void cmbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuarioActionPerformed

    public void txtDescricaoBreveActionPerformed(java.awt.event.ActionEvent evt) {
        //TODO
    }
    
    public void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {
        //TODO
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBem;
    private javax.swing.JButton btnCancelaLeilao;
    private javax.swing.JButton btnSalvarLeilao;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JComboBox cmbForma;
    private javax.swing.JComboBox cmbNatureza;
    private javax.swing.JComboBox cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lstBens;
    private javax.swing.JTextField txtDataFim;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtDescricaoBreve;
    private javax.swing.JTextArea txtDescricaoCompleta;
    private javax.swing.JTextField txtHoraFim;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtValorLote;
    // End of variables declaration//GEN-END:variables
}
