/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Business.BusinessException;
import Business.Fachada;
import Business.Validadores.ValidaLance;
import Domain.Lance;
import Domain.Leilao;
import Domain.Usuario;
import java.math.BigDecimal;
import java.sql.Time;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class DlgLance extends javax.swing.JDialog {

    /**
     * Creates new form DlgLance
     */
    public DlgLance(java.awt.Frame parent, boolean modal, Fachada fachada) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.fachada = fachada;
        try {
            populaCampos();
        } catch (BusinessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private final Fachada fachada;

    private void populaCampos() throws BusinessException {

        for (Usuario usu : fachada.buscarTodosUsuarios()) {
            cmbUsuario.addItem(usu);
        }

        for (Leilao l : fachada.buscarTodosLeiloes()) {
            cmbCodigoLeilao.addItem(l);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCodigoLeilao = new javax.swing.JComboBox();
        txtValorLance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarLance = new javax.swing.JButton();
        btnCancelarLance = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbUsuario = new javax.swing.JComboBox();

        jLabel1.setText("Novo Lance");

        jLabel2.setText("Código Leilão:");

        txtValorLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorLanceActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Lance:");

        btnSalvarLance.setText("Salvar");
        btnSalvarLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLanceActionPerformed(evt);
            }
        });

        btnCancelarLance.setText("Cancelar");
        btnCancelarLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLanceActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuário:");

        cmbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnSalvarLance)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarLance))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValorLance)
                            .addComponent(cmbCodigoLeilao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUsuario, 0, 170, Short.MAX_VALUE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbCodigoLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorLance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarLance)
                    .addComponent(btnCancelarLance))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorLanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorLanceActionPerformed

    private void btnCancelarLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLanceActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarLanceActionPerformed

    private void cmbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuarioActionPerformed

    private void btnSalvarLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLanceActionPerformed
        if (!ValidaLance.getInstance().validarValor(new BigDecimal(txtValorLance.getText()))) {
            JOptionPane.showMessageDialog(null, "Valor passado esta incorreto!");
        } else {

            Date date = Calendar.getInstance().getTime();
            Time time = new Time(Calendar.getInstance().getTimeInMillis());

            Lance lance = new Lance(0, date, time, new BigDecimal(txtValorLance.getText()), ((Usuario) cmbUsuario.getSelectedItem()), ((Leilao) cmbCodigoLeilao.getSelectedItem()));

            try {
                fachada.criarLance(lance);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Criado com sucesso.");
            } catch (BusinessException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnSalvarLanceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLance;
    private javax.swing.JButton btnSalvarLance;
    private javax.swing.JComboBox cmbCodigoLeilao;
    private javax.swing.JComboBox cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtValorLance;
    // End of variables declaration//GEN-END:variables
}
